ALTER SESSION SET CONTAINER = FREEPDB1;
/

ALTER SESSION SET CURRENT_SCHEMA = APPUSER;
/

INSERT INTO "CUSTOMERS" ("ID", "CUSTOMER_NAME") VALUES (1, 'John Doe');
INSERT INTO "CUSTOMERS" ("ID", "CUSTOMER_NAME") VALUES (2, 'Jane Smith');

INSERT INTO "ACCOUNTS" ("ID", "ACCOUNT_NUMBER", "BALANCE", "CUSTOMER_ID") VALUES (1, '1001', 100000, 1);
INSERT INTO "ACCOUNTS" ("ID", "ACCOUNT_NUMBER", "BALANCE", "CUSTOMER_ID") VALUES (2, '1002', 50000, 2);

COMMIT;
/
